### ISSUE TITLE
sh scripts/compile_engines.sh

### ISSUE THREAD

**Issue by eirinistam** [junipertcy/bipartiteSBM-MCMC#2]
Hi !!
When I run the following command sh scripts/compile_engines.sh
I receive 
scripts/compile_engines.sh: 3: scripts/compile_engines.sh: pushd: not found
scripts/compile_engines.sh: 4: scripts/compile_engines.sh: pushd: not found

I cannot understand why.
Thank you.

**Comment by junipertcy** [comment]
@eirinistam Some machines do not have pushd/popd installed by default. I have replaced them with cd/cd -; it should be alright now.
